#!/usr/bin/env bash
# =============================================================================
# Pull this environment's secrets into /opt/medicraft/.env.app.
#
# Run on the server before every `compose up`, using the instance role. No
# credential is stored anywhere on the box.
#
# WHY HOST-SIDE AND NOT AN ENTRYPOINT IN THE IMAGE
# ------------------------------------------------
# An entrypoint that fetches secrets itself needs the AWS CLI or SDK inside
# the runtime image — which is a deliberately minimal standalone Next build
# with no package manager — and it needs the container to reach the instance
# metadata service, which is an extra network hop that fails closed unless
# the hop limit is raised.
#
# The security difference is close to nil: either way the values end up in
# the container's environment, where `docker inspect` can read them. This
# way the image stays clean and the fetch is one place, auditable, with a
# 0600 file owned by one user as the only artefact.
#
# Nothing is printed. The file is written with a restrictive umask.
# =============================================================================
set -euo pipefail
umask 077

source /opt/medicraft/.env.infra   # AWS_REGION, ENV_NAME, ECR_REGISTRY

OUT=/opt/medicraft/.env.app
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

get() {
  aws secretsmanager get-secret-value \
    --secret-id "medicraft/${ENV_NAME}/$1" \
    --query SecretString --output text --region "$AWS_REGION"
}

{
  echo "# Generated by fetch-secrets.sh at $(date -u +%FT%TZ). Do not edit."
  for name in POSTGRES_PASSWORD AUTH_SECRET FIELD_ENCRYPTION_KEY RESEND_API_KEY CRON_SECRET; do
    value=$(get "$name") || { echo "FAILED to read $name" >&2; exit 1; }
    [ -n "$value" ] || { echo "$name is empty in Secrets Manager" >&2; exit 1; }
    printf '%s=%s\n' "$name" "$value"
  done
} > "$TMP"

install -m 600 -o ec2-user -g ec2-user "$TMP" "$OUT"

# --- The interpolation file ------------------------------------------------
# Compose reads `.env` from the project directory automatically, and
# docker-compose.yml interpolates POSTGRES_PASSWORD and APP_IMAGE at parse
# time — so WITHOUT this file every `docker compose` command fails, including
# `logs` and `ps`. An operator SSHing in to see why the site is down should
# not first have to know which variables to export.
#
# APP_IMAGE is preserved if it is already set; the deploy owns that line.
EXISTING_IMAGE=$(grep -E '^APP_IMAGE=' /opt/medicraft/.env 2>/dev/null || true)
PW=$(grep -E '^POSTGRES_PASSWORD=' "$OUT" | cut -d= -f2-)

{
  echo "# Generated by fetch-secrets.sh. Read automatically by docker compose."
  echo "POSTGRES_PASSWORD=$PW"
  [ -n "$EXISTING_IMAGE" ] && echo "$EXISTING_IMAGE"
} > "$TMP"
install -m 600 -o ec2-user -g ec2-user "$TMP" /opt/medicraft/.env

echo "Wrote $OUT ($(grep -c '=' "$OUT") values) and /opt/medicraft/.env"
