/* --- Postgres --------------------------------------------------------------
   Private, encrypted, backed up. Nothing outside the VPC can reach it: the
   security group allows 5432 from the App Runner connector's group and from
   nothing else, and the instance has no public address to resolve.
   ------------------------------------------------------------------------ */

resource "aws_db_subnet_group" "main" {
  name       = local.name
  subnet_ids = aws_subnet.private[*].id
  tags       = local.tags
}

resource "aws_security_group" "db" {
  name        = "${local.name}-db"
  description = "Postgres, reachable only from the App Runner connector"
  vpc_id      = aws_vpc.main.id
  tags        = merge(local.tags, { Name = "${local.name}-db" })
}

resource "aws_security_group" "apprunner" {
  name        = "${local.name}-apprunner"
  description = "Egress for the App Runner VPC connector"
  vpc_id      = aws_vpc.main.id

  # Outbound only. The connector initiates to Postgres, to Resend and to S3;
  # nothing dials in.
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(local.tags, { Name = "${local.name}-apprunner" })
}

# Declared separately rather than inline, because two security groups
# referencing each other inline is a cycle Terraform cannot resolve.
resource "aws_security_group_rule" "db_from_apprunner" {
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.db.id
  source_security_group_id = aws_security_group.apprunner.id
  description              = "Postgres from the App Runner connector"
}

resource "aws_db_instance" "main" {
  identifier     = local.name
  engine         = "postgres"
  engine_version = "16"
  instance_class = var.db_instance_class

  allocated_storage     = 20
  max_allocated_storage = 100 # autoscale rather than fill up at 3am
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = "medicraft"
  username = "medicraft"
  # Generated by AWS and stored in a managed secret. The password never
  # exists in Terraform state, which a `password = random_password...` would
  # have put there in plaintext.
  manage_master_user_password = true

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.db.id]
  publicly_accessible    = false

  # Production keeps a month; staging a week. Both keep something — a
  # database holding prescriber records with backups off is not a saving.
  backup_retention_period = var.env_name == "production" ? 30 : 7
  backup_window           = "07:00-08:00" # 3am Eastern, outside pharmacy hours
  maintenance_window      = "sun:08:00-sun:09:00"

  # Production refuses to be destroyed by a stray `terraform destroy` and
  # leaves a final snapshot behind. Staging is meant to be disposable.
  deletion_protection       = var.env_name == "production"
  skip_final_snapshot       = var.env_name != "production"
  final_snapshot_identifier = var.env_name == "production" ? "${local.name}-final" : null

  auto_minor_version_upgrade   = true
  performance_insights_enabled = var.env_name == "production"

  tags = local.tags
}

output "db_master_secret_arn" {
  description = "AWS-managed secret holding the master password. Build DATABASE_URL from it."
  value       = aws_db_instance.main.master_user_secret[0].secret_arn
}

output "db_endpoint" {
  value = aws_db_instance.main.endpoint
}
